services:
  wedding-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-backend
    ports:
      - "7777:7777"
    environment:
      WEDDING_API_KEY: ${WEDDING_API_KEY}
    volumes:
      - ./guests.json:/app/guests.json
    restart: unless-stopped
